version: "3"

services:                                                                               
 #  db:
  #   image: postgres:9.6
   #  env_file: .env 
    # ports:
     #  - "5432:5432"

   graphdb:
     image: neo4j:3.1
     ports:
       - "7474:7474"
       - "7687:7687"

   api:
     build:
       context: ./dpa-flask
       dockerfile: Dockerfile2
     #env_file: .env
     ports:
       - "8080:8080"
