version: "3"

services:     
   backend:
      build:
        context: ./docker-flask
        dockerfile: Dockerfile
      env_file: .env
      ports:
        - "8080:8080"

   api:
      build:
        context: ./docker-shiny
        dockerfile: Dockerfile
      ports:
        - "3838:3838"
     #env_file: .env
