version: "3"

services:     
   backend:
      image: localhost:5000/ambiente_backend:v0.1
     env_file: .env
     ports:
        - "8080:8080"

   api:
      image: localhost:5000/ambiente_api:v0.1
     env_file: .env
     ports:
        - "3838:3838"
     #env_file: .env

networks:
  dpa:
    external: true
