version: "3"

services: 
   bd:
     image: localhost:5000/shinyflaskpostgresqlapp_bd:1.0 #jalf/tasks05
     env_file: .env
     ports:
        - "5432:5432"
     networks:
        - dpap1

   backend:
     image: localhost:5000/shinyflaskpostgresqlapp_backend:1.0 #jalf/tasks05
     env_file: .env
     ports:
        - "8080:8080"
     networks:
        - dpap1

   api:
     image: localhost:5000/shinyflaskpostgresqlapp_api:1.0
     env_file: .env
     ports:
        - "3838:3838"
     networks:
        - dpap1

networks:
  dpap1:
    external: true
