version: "3"

services: 
   bd:
     image: localhost:5000/shinyflaskpostgresqlapp_bd:v0.1 #jalf/tasks05
     env_file: .env
     ports:
        - "5432:5432"
     networks:
        - dpap1

   backend:
     image: localhost:5000/shinyflaskpostgresqlapp_backend:v0.1 #jalf/tasks05
     env_file: .env
     ports:
        - "8080:8080"
     networks:
        - dpap1

   api:
     image: localhost:5000/shinyflaskpostgresqlapp_api:v0.1
     env_file: .env
     ports:
        - "3838:3838"
     networks:
        - dpap1

networks:
  dpap1:
    external: true
